version: "3.6"
services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 5431:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
