
version: "3.6"
services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: